### ISSUE TITLE
Informazione

### ISSUE THREAD

**Issue by kingofkillers91** [federicotorrielli/better-chatgpt-telegram-bot#1]
Ciao, in che senso questa è una versione migliorata del bot di amazingpaddy?
Altra domanda, posso aggiungere il bot nei gruppi?
Grazie

**Comment by federicotorrielli** [comment]
Ciao. Questo bot è un WIP upgrade su quello di amazingpaddy. Più che altro, funziona, al contrario del suo. Ho introdotto un progress message e fatto un refactor del codice. Nelle prossime settimane aggiungo ancora qualcosa ma ovviamente accetto suggerimenti :)

**Comment by federicotorrielli** [comment]
Closing this as solved.
