### ISSUE TITLE
Errore al lancio dello script

### ISSUE THREAD

**Issue by kingofkillers91** [federicotorrielli/better-chatgpt-telegram-bot#2]
Ciao federico,
mi succede questo nonostante abbia settato la path corretta, ho pure provato a spostare il json in un'altra directory.
─# python bingbot.py
Traceback (most recent call last):
  File "/home/alessandro/Desktop/better-chatgpt-telegram-bot/bingbot.py", line 15, in <module>
    gbot = Chatbot(cookiePath=cookies_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alessandro/Myproject1/lib/python3.11/site-packages/EdgeGPT.py", line 269, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alessandro/Myproject1/lib/python3.11/site-packages/EdgeGPT.py", line 169, in __init__
    open(cookiePath, encoding="utf8").read()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '</home/alessandro/Desktop/EdgeGPT/cookie.json>'
Prima di questa path avevo messo il json dentro la directory di better-chatgpt-telegram.

Cosi è come l'ho settato nel file bingbot: 
# Update your cookies.json path here
cookies_path = '</home/alessandro/Desktop/EdgeGPT/cookie.json>'
gbot = Chatbot(cookiePath=cookies_path)

Non riesco a capire che non va. Grazie

**Comment by federicotorrielli** [comment]
La path non deve stare tra le parentesi uncinate <>, dovrebbe solo essere: 
`cookies_path = '/home/alessandro/Desktop/EdgeGPT/cookie.json'`
