### ISSUE TITLE
Informazione.

### ISSUE THREAD

**Issue by kingofkillers91** [federicotorrielli/better-chatgpt-telegram-bot#3]
Innazitutto grazie perchè adesso mi funziona il bot. 
Ma volevo chiederti una cosa, ho messo il mio bot in un gruppo, ma due persone di queste non hanno un username vero e proprio ma posso vedere solo il loro numero di telefono e al massimo i loro ID personale. Ho provato  ad inserire sia ID che il numero di telefono ma il bot non li riconosce. Hai qualche idea?
Grazie
![Immagine 2023-03-13 000820](https://user-images.githubusercontent.com/48602339/224579603-a460c2df-dd36-4cdc-b6c4-8eae24e36a22.png)

**Comment by federicotorrielli** [comment]
Il bot non e' correntemente compatibile con gruppi, e non ne consiglio neanche l'utilizzo per il futuro, dato che fa uso dei tuoi cookie e tuoi dati privati, anche, per generare.

**Comment by kingofkillers91** [comment]
e' un gruppo di amici privato che di informatica sanno poco e niente.Nell'attesa che esca un bot compatibile per i gruppi,  C'è la possibilità che io possa inserire il loro id oppure disabilitare la restrizione del tutto?

**Comment by federicotorrielli** [comment]
Non può uscire un "bot compatibile per i gruppi", il bot stesso è basato su un reverse-engineering di bing chat, che è una chat privata...
